### ISSUE TITLE
FTP has no date information

### ISSUE THREAD

**Issue by pixelmasher** [joel16/3DShell#11]
FTP function removes the date information when I copy something from the 3DS to computer. It also shows all the date being 1970-01-01 in WinSCP. In GodMode9 I can see the proper date.

I'm using the 3dsx version of 2.00 beta. I'm not sure what you mean by "SM/FS patches", but I have game patching enabled in Luma 3DS 8.1.1.

I like how it combines CTRExplorer and FTPD.

**Comment by joel16** [comment]
Game patching is something different, by SM/FS patches I mean you need to open rosalina, open process patches and enable both FS/SM patches. Also, I'd recommend using the CIA since 3dsx versions can't access CTRNAND.

"It also shows all the date being 1970-01-01 in WinSCP. In GodMode9 I can see the proper date."
I just checked using WinSCP it does show 1970, and it's the same with FileZilla as well. (I totally forgot about timestamps here, my bad) This is something I'll need to  look into.
Although I don't get what you mean GodMode9 displays the proper date? Does 3DShell not display the proper file dates? I just checked the .3dsx version and the file dates are displayed correctly here. I did mention the files such as 'Nintendo 3DS' and 'DCIM' (the one the 3DS itself creates for you) displays incorrect timestamps.

**Comment by pixelmasher** [comment]
Ok. I turned on the patches in Rosalina. It shows the battery percentage and things correctly now. I like using the 3dsx version. The file date is correct, but just gets displayed weird when connected using built in FTP. I was mistaken about GodMode9. Maybe I was thinking of FTPD as it show the dates correctly. It's not a huge issue. It just seemed weird since you said it's FTPD code and I don't have the issue using 3dsx of FTPD v2.2.

**Comment by joel16** [comment]
Well I did make a few modifications here and there, I might have derped somewhere so I'll take a look. Thanks for reporting.

**Comment by pixelmasher** [comment]
Thank you for making this wonderful homebrew and for your excellent contribution to the scene. Hope to see it fixed in the next release.

**Comment by joel16** [comment]
Fixed with commit https://github.com/joel16/3DShell/commit/4008c884bb7d636008e2a25359edd5db31f18398

Somehow the console outputs actually fixed this, oh well.
