### ISSUE TITLE
Does not display special character properly.

### ISSUE THREAD

**Issue by pixelmasher** [joel16/3DShell#12]
I tried to delete a folder with ® in the name while connected to FTP. It couldn't delete it, I tried it in FTPD and it worked fine. Wanted to check if it was FTP problem or 3DShell problem. When I tried to delete it from 3DShell, I noticed it would not display anything in the folder name starting from ®. It cut off the folder name in the middle. Since it's not recognizing the character, it can't deal with it.

**Comment by joel16** [comment]
Thanks for reporting, I'm aware of this issue, it's a problem with supporting multi-byte characters. I noticed this when I set my username to Joél, and it would just display it as "Jo". ignoring everything after the multi-byte character. I have two ways to go about fixing this, and it'll most definitely be fixed in the next release. While I'm here I also wanted to mention, that FTP time-stamp issue is still being a problem. I did try and fix it, but couldn't identify what's causing the issue so I'll need to do more research there. 

Also with college coming up next week, I won't have much time to work on this as I used to, so development may be slower.

**Comment by pixelmasher** [comment]
I'm thankful you're spending your time developing stuff. Since there are alternatives, it's not a big deal. It's good to have alternatives. I'm happy you're keeping the homebrews updated and fixing bugs. It's more than what some other devs are doing. Take your time.

**Comment by joel16** [comment]
Hey, I totally forgot about this issue, but it's fixed in one of the previous commits. Not sure which one exactly, but it's definitely been fixed. I believe I fixed it while I made some changes to the utf16-utf8 conversion at some point. (Tested renaming via FTP, which also worked)

![proof](https://imgur.com/H58QzPJ)

Expect a new release very soon! :P
