### ISSUE TITLE
Trouble with accented characters

### ISSUE THREAD

**Issue by SpiredMoth** [joel16/3DShell#32]
The app mostly freezes when trying to access folders containing accented characters (like é). None of the folder's contents get listed and the only input that still responds are the SD, NAND, and Search buttons on the touch screen.
![3dshell-2018-07-20_19-10-38 576](https://user-images.githubusercontent.com/8207460/43031285-8e085ca2-8c53-11e8-9ef4-fb6ea41887f5.png)

Makes it hard to manage Checkpoint save backups of games like Pokémon (renaming the save folders, etc.)

I primarily use the Rosalina version, but tried with the CIA version to make sure it wasn't unique to the 3dsx build.

**Comment by joel16** [comment]
Sorry about that, I swore I fixed this before. I'll have a look at this again. Looking at your screenshot, it properly displays the accented characters (before I fixed an issue similar to this would just display a black box instead of the accented character). Anyways, there seems to be a problem opening it, I'll have a look.

**Comment by SpiredMoth** [comment]
Sorry for the late response, been without internet all weekend because of my move.

The fix worked.

**Comment by joel16** [comment]
Thanks for confirming.
